version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: vidtrans_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  migrate:
    build:
      context: ./server
      dockerfile: DockerFile
    container_name: vidtrans_migrate
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command:
      ["sh", "./wait-for.sh", "postgres", "npx", "prisma", "migrate", "deploy"]
    restart: "no"

  api:
    build:
      context: ./server
      dockerfile: DockerFile
    container_name: vidtrans_api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - migrate
    environment:
      NODE_ENV: production
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_PRODUCTION_BUCKET_NAME: ${AWS_PRODUCTION_BUCKET_NAME}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./server/videos:/app/videos
    restart: unless-stopped
    command: ["sh", "./wait-for.sh", "postgres", "node", "server.js"]

  poller:
    build:
      context: ./server
      dockerfile: DockerFile
    container_name: vidtrans_poller
    depends_on:
      - postgres
      - migrate
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_PRODUCTION_BUCKET_NAME: ${AWS_PRODUCTION_BUCKET_NAME}
      QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/107346957471/VidTransQueue
    volumes:
      - ./server/videos:/app/videos
    restart: unless-stopped
    command: ["sh", "./wait-for.sh", "postgres", "node", "poller/poller.js"]

  worker:
    build:
      context: ./server
      dockerfile: DockerFile
    container_name: vidtrans_worker
    depends_on:
      - postgres
      - migrate
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_PRODUCTION_BUCKET_NAME: ${AWS_PRODUCTION_BUCKET_NAME}
    volumes:
      - ./server/videos:/app/videos
    restart: unless-stopped
    command: ["sh", "./wait-for.sh", "postgres", "node", "worker/worker.js"]

volumes:
  postgres_data:
