FROM node:18-slim

RUN apt-get update \
  && apt-get install -y ffmpeg postgresql-client \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

CMD ["node", "server.js"]
